# Use an official Node.js runtime as a parent image
FROM node:21.7.3-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

COPY vite.config.js ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

EXPOSE 8080

# Start your React app
CMD ["npm", "run", "dev"]


